### PR TITLE
Chatter Test

### PR DESCRIPTION
**Pull request by dduleone**
DO NOT EXECUTE THIS PULL REQUEST!

@mduleone

### CODE REVIEW

**Comment by dduleone** [comment]
Now, we can chat in here, and it will just update, inline.

**Comment by mduleone** [comment]
forreals?

**Comment by dduleone** [comment]
Yup

**Comment by dduleone** [comment]
For actually collaborating, you can even leave comments attached to specific lines of code.

**Comment by mduleone** [comment]
oooh

**Comment by mduleone** [comment]
and ctrl+enter sends

**Comment by mduleone** [comment]
that's kind of frustrating., but I guess we can get over it

**Comment by dduleone** [comment]
We'd probably want to make a dedicated project. I'd pay for the private repo. And we could store all sorts of documents or whatever we'd want. We'll also want to turn off the email notifications. :P

**Comment by dduleone** [comment]
I'm not saying this is necessarily a better way to chat. But it's something to keep in mind, if Ally ever loses access to Google Docs again.

**Comment by mduleone** [comment]
holy shit email spam lol

**Comment by dduleone** [comment]
lol I muted the thread (button at the bottom) type a few more comments? I wanna see if I get emails.

**Comment by mduleone** [comment]
test

**Comment by mduleone** [comment]
does muting work?

**Comment by mduleone** [comment]
that would be awesome

**Comment by dduleone** [comment]
Blah - it didn't update the page and it did send me an email lol

**Comment by mduleone** [comment]
lol this was fun to read.

**Pull request closed without merging**
